language: java
sudo: required

matrix:
  include:
    - jdk: oraclejdk8
  allow_failures:
    - jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer

notifications:
  email: false
